#!/usr/bin/env python
# -*- coding: utf-8 -*-
import SourceBuilder
import logging
import os
import sys

logging.basicConfig(format="[%(asctime)s] %(message)s", level=logging.DEBUG)
#fmt = logging.Formatter("[%(asctime)s] %(message)s")
#logger = logging.getLogger("SourceBuilder")
#handler = CursesOutput(stdscr)
#logger.addHandler(handler)
builder = SourceBuilder.builder()
builder.build()

#if len(sys.argv) >= 2:
#	builder = SourceBuilder.builder(sys.argv[1])
#else:
#	builder = SourceBuilder.builder(os.getcwd())
#builder.build()

#Possible uses of the 'build' command:
#build source.tar.bz2 - Builds and installs source.tar.bz2
#build - Builds the current directory.
#build /path/to/source - Builds the given source
